spring:
  h2:
    console:
      enabled: true
  datasource:
    hikari:
      jdbc-url:  jdbc:h2:tcp://localhost/~/test
      driver-class-name: org.h2.Driver
      username: sa
      password:


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
